### ISSUE TITLE
[Question] About the signs content

### ISSUE THREAD

**Issue by joex92** [TQNL/Copy-Signs#1]
If the sign to be copied has content on both sides, will both sides of the signs be copied too?
also, if I have more than 1 sign item, will the content be bypassed to all the holding signs? or just 1?

(I believe it this would be better suited on a discussion tab, but you haven't enabled discussions here)

**Comment by TQNL** [comment]
a) yes, both sides are copied over
b) the content will copy over to all held signs
sorry for responding this late :)

**Comment by joex92** [comment]
no problem... thanks for answering... 👍🏼
